<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { api, type Overview, type User, type Node, type Release, type Audit, type Device } from './api';
const auth=ref(false),role=ref(''),token=ref(''),page=ref('overview'),busy=ref(false),error=ref('');
const overview=ref<Overview>({devices:[],sessions:[],online:0,version:'',backend:'',memory_bytes:0,goroutines:0,limitations:[]});
const users=ref<User[]>([]),nodes=ref<Node[]>([]),releases=ref<Release[]>([]),audit=ref<Audit[]>([]);
const settings=ref({max_sessions:2048,banner:''}),config=ref<Record<string,unknown>>({});
const filter=ref(''),newUser=ref({name:'',role:'viewer'}),newNode=ref<Node>({id:'',name:'',address:'https://',region:'',enabled:true}),releaseText=ref('');
const edit=ref<Device|null>(null),showDevice=ref(false),newToken=ref('');let timer:ReturnType<typeof setInterval>|undefined;let refreshing=false;
const pages=[['overview','运行概览'],['devices','设备管理'],['sessions','在线会话'],['users','用户权限'],['nodes','节点配置'],['releases','签名版本'],['audit','操作日志'],['config','系统设置']];
const peers=computed(()=>overview.value.devices.filter(p=>`${p.device.name} ${p.device.id}`.toLowerCase().includes(filter.value.toLowerCase())));
const active=computed(()=>overview.value.sessions.filter(s=>!s.closed));
const time=(n:number)=>n>0?new Date(n*1000).toLocaleString():'—';
async function guarded(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:String(e);ElMessage.error(error.value)}finally{busy.value=false}}
async function refresh(){if(!auth.value||refreshing)return;refreshing=true;try{overview.value=await api<Overview>('overview');error.value=''}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{refreshing=false}}
async function select(key:string){page.value=key;await guarded(async()=>{if(key==='users')users.value=await api<User[]>('users');if(key==='nodes')nodes.value=(await api<{nodes:Node[]}>('nodes')).nodes;if(key==='releases')releases.value=await api<Release[]>('releases');if(key==='audit')audit.value=await api<Audit[]>('audit');if(key==='config'){const v=await api<{settings:{max_sessions:number;banner:string}} & Record<string,unknown>>('config');settings.value=v.settings;config.value=v}await refresh()})}
async function login(){await guarded(async()=>{const result=await api<{role:string}>('login','POST',{token:token.value});token.value='';role.value=result.role;auth.value=true;await refresh()})}
async function logout(){await guarded(async()=>{await api('logout','POST',{});auth.value=false;overview.value.devices=[];newToken.value=''})}
async function saveDevice(){if(!edit.value)return;const d=edit.value;await guarded(async()=>{await api('device','POST',{id:d.id,name:d.name,owner:d.owner||'',disabled:d.disabled});showDevice.value=false;await refresh();ElMessage.success('设备设置已保存')})}
async function closeSession(id:string){try{await ElMessageBox.confirm('中继连接将关闭，客户端将在会话状态检查后停止。确认断开？','断开会话',{type:'warning'});await guarded(async()=>{await api('session-close','POST',{id});await refresh()})}catch{}}
async function addUser(){await guarded(async()=>{const result=await api<{token:string}>('users','POST',newUser.value);newToken.value=result.token;newUser.value={name:'',role:'viewer'};users.value=await api<User[]>('users')})}
async function removeUser(u:User){try{await ElMessageBox.confirm(`撤销 ${u.name} 的管理访问？设备本地授权不受影响。`,'删除用户',{type:'warning'});await guarded(async()=>{await api(`users?id=${encodeURIComponent(u.id)}`,'DELETE');users.value=await api<User[]>('users')})}catch{}}
async function saveNode(){await guarded(async()=>{await api('nodes','POST',newNode.value);nodes.value=(await api<{nodes:Node[]}>('nodes')).nodes;newNode.value={id:'',name:'',address:'https://',region:'',enabled:true}})}
async function removeNode(n:Node){try{await ElMessageBox.confirm(`删除节点记录 ${n.name}？`,'删除记录');await guarded(async()=>{await api(`nodes?id=${encodeURIComponent(n.id)}`,'DELETE');nodes.value=(await api<{nodes:Node[]}>('nodes')).nodes})}catch{}}
async function publish(){await guarded(async()=>{const value:unknown=JSON.parse(releaseText.value);await api('releases','POST',value);releaseText.value='';releases.value=await api<Release[]>('releases');ElMessage.success('签名发布信息已保存')})}
onMounted(async()=>{try{const me=await api<{role:string}>('me');role.value=me.role;auth.value=true;await refresh()}catch{}timer=setInterval(refresh,5000)});onUnmounted(()=>{if(timer)clearInterval(timer)});
</script>
<template>
 <main v-if="!auth" class="login"><section><div class="wordmark">RemoteDesk</div><h1>管理控制台</h1><p>设备、会话与签名版本管理。登录凭据仅用于管理，不授予远程控制权限。</p><el-input v-model="token" type="password" show-password placeholder="管理员或用户访问令牌" @keyup.enter="login"/><el-button type="primary" :loading="busy" @click="login">登录</el-button><el-alert v-if="error" :title="error" type="error" :closable="false"/></section></main>
 <el-container v-else class="shell"><el-aside width="216px"><div class="wordmark">RemoteDesk<span>CONTROL CENTER</span></div><el-menu :default-active="page" @select="select"><template v-for="[key,label] in pages" :key="key"><el-menu-item v-if="key!=='users'||role==='admin'" :index="key">{{label}}</el-menu-item></template></el-menu><footer>{{overview.version}}<br>{{role}}</footer></el-aside>
 <el-container><el-header><span>{{pages.find(p=>p[0]===page)?.[1]}}</span><div><el-button text @click="refresh">刷新</el-button><el-button text @click="logout">退出</el-button></div></el-header><el-main v-loading="busy"><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <template v-if="page==='overview'"><div class="metrics"><article><label>在线设备</label><b>{{overview.online}}</b></article><article><label>已注册设备</label><b>{{overview.devices.length}}</b></article><article><label>活动会话</label><b>{{active.length}}</b></article><article><label>服务进程内存</label><b>{{(overview.memory_bytes/1048576).toFixed(1)}}<small> MB</small></b></article></div><section class="panel"><h2>运行状态</h2><p>{{overview.backend}}</p><p>活跃 Go 协程：{{overview.goroutines}}</p><el-alert title="工程验证状态" type="info" :closable="false"><p v-for="line in overview.limitations" :key="line">{{line}}</p><p>节点页面保存配置记录，当前未启用跨节点信令路由。性能数据不使用模拟值。</p></el-alert></section></template>
 <template v-if="page==='devices'"><div class="toolbar"><el-input v-model="filter" placeholder="搜索名称或设备 ID"/></div><el-table :data="peers"><el-table-column prop="device.name" label="设备"/><el-table-column prop="device.id" label="设备 ID"/><el-table-column label="在线状态"><template #default="{row}"><el-tag :type="row.online?'success':'info'">{{row.online?'在线':'离线'}}</el-tag></template></el-table-column><el-table-column label="上次在线"><template #default="{row}">{{time(row.last_seen)}}</template></el-table-column><el-table-column prop="device.owner" label="归属"/><el-table-column label="操作"><template #default="{row}"><el-button :disabled="role!=='admin'" text @click="edit={...row.device};showDevice=true">编辑</el-button></template></el-table-column></el-table></template>
 <template v-if="page==='sessions'"><el-table :data="overview.sessions"><el-table-column prop="kind" label="类型"/><el-table-column prop="from" label="控制端"/><el-table-column prop="to" label="被控端"/><el-table-column label="状态"><template #default="{row}">{{row.closed?'已关闭':row.paired?'中继已配对':'协商或直连'}}</template></el-table-column><el-table-column label="会话期限"><template #default="{row}">{{time(row.expires_at)}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button type="danger" text :disabled="role==='viewer'||row.closed" @click="closeSession(row.id)">断开</el-button></template></el-table-column></el-table></template>
 <template v-if="page==='users'"><section class="panel"><h2>创建管理用户</h2><div class="toolbar"><el-input v-model="newUser.name" placeholder="用户名称"/><el-select v-model="newUser.role"><el-option label="只读" value="viewer"/><el-option label="会话操作员" value="operator"/><el-option label="管理员" value="admin"/></el-select><el-button type="primary" @click="addUser">创建</el-button></div><el-alert v-if="newToken" type="warning" title="令牌仅显示一次，请保存到私密位置" :closable="false"><el-input :model-value="newToken" type="password" show-password readonly/><el-button text @click="newToken=''">隐藏令牌</el-button></el-alert></section><el-table :data="users"><el-table-column prop="name" label="用户"/><el-table-column prop="role" label="角色"/><el-table-column label="创建时间"><template #default="{row}">{{time(row.created)}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button type="danger" text @click="removeUser(row)">撤销访问</el-button></template></el-table-column></el-table></template>
 <template v-if="page==='nodes'"><el-alert type="info" title="当前为节点配置目录，不代表已经启用多节点路由或故障转移。" :closable="false"/><section v-if="role==='admin'" class="panel"><div class="toolbar"><el-input v-model="newNode.name" placeholder="节点名称"/><el-input v-model="newNode.address" placeholder="HTTPS 地址"/><el-input v-model="newNode.region" placeholder="地区"/><el-button type="primary" @click="saveNode">保存节点</el-button></div></section><el-table :data="nodes"><el-table-column prop="name" label="节点"/><el-table-column prop="address" label="地址"/><el-table-column prop="region" label="地区"/><el-table-column label="操作"><template #default="{row}"><el-button :disabled="role!=='admin'" text @click="newNode={...row}">编辑</el-button><el-button :disabled="role!=='admin'" type="danger" text @click="removeNode(row)">删除</el-button></template></el-table-column></el-table></template>
 <template v-if="page==='releases'"><section v-if="role==='admin'" class="panel"><h2>发布离线签名清单</h2><p>使用 release-sign 生成清单。服务器验证预置公钥、有效期和递增序号；客户端仍会独立验签。</p><el-input v-model="releaseText" type="textarea" :rows="7" placeholder="粘贴带 manifest 和 signature 的 JSON"/><el-button type="primary" @click="publish">验证并发布</el-button></section><el-table :data="releases"><el-table-column prop="manifest.version" label="版本"/><el-table-column prop="manifest.sequence" label="序号"/><el-table-column prop="manifest.platform" label="平台"/><el-table-column label="有效期"><template #default="{row}">{{time(row.manifest.expires_at)}}</template></el-table-column></el-table></template>
 <template v-if="page==='audit'"><el-table :data="[...audit].reverse()"><el-table-column label="时间"><template #default="{row}">{{time(row.at)}}</template></el-table-column><el-table-column prop="actor" label="操作者"/><el-table-column prop="action" label="操作"/><el-table-column prop="object" label="对象"/></el-table></template>
 <template v-if="page==='config'"><section class="panel"><h2>会话与公告设置</h2><el-form label-position="top"><el-form-item label="最多活动/保留会话"><el-input-number v-model="settings.max_sessions" :min="1" :max="10000" :disabled="role!=='admin'"/></el-form-item><el-form-item label="管理公告"><el-input v-model="settings.banner" maxlength="500" type="textarea" :disabled="role!=='admin'"/></el-form-item><el-button type="primary" :disabled="role!=='admin'" @click="guarded(async()=>{await api('config','POST',settings);ElMessage.success('设置已保存')})">保存</el-button></el-form><el-divider/><p>HTTPS 监听：{{config.listen}}</p><p>STUN / UDP 中继：{{config.stun}}</p><p>更新签名公钥：{{config.update_signing_configured?'已配置':'未配置'}}</p><p>设备私钥仅保存在设备本机。TLS 服务器私钥仍由服务器私密配置管理。</p></section></template>
 </el-main></el-container></el-container>
 <el-dialog v-model="showDevice" title="设备设置" width="480px"><el-form v-if="edit" label-position="top"><el-form-item label="设备名称"><el-input v-model="edit.name"/></el-form-item><el-form-item label="归属备注"><el-input v-model="edit.owner"/></el-form-item><el-form-item label="禁止新连接"><el-switch v-model="edit.disabled"/></el-form-item><p>服务器设置不修改设备私钥，也不替代本机远控授权。</p></el-form><template #footer><el-button @click="showDevice=false">取消</el-button><el-button type="primary" @click="saveDevice">保存</el-button></template></el-dialog>
</template>
