<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Grid, Monitor, Connection, TrendCharts, Document, Setting, Lock, Upload, Refresh, Fold, Moon, Sunny, SwitchButton, Search, Download, User } from '@element-plus/icons-vue'
import Sparkline from './Sparkline.vue'
import DeviceDetails from './DeviceDetails.vue'
import { connectionStatus, csvCell, formatBytes, telemetryState } from './connection.mjs'
import type { Audit, Device, DeviceMeta, Overview, Release, Sample, Settings } from './types'

const menus=[{id:'overview',name:'运行总览',icon:Grid},{id:'nodes',name:'服务器节点',icon:Monitor},{id:'devices',name:'设备管理',icon:Monitor},{id:'sessions',name:'会话与中继',icon:Connection},{id:'metrics',name:'性能监控',icon:TrendCharts},{id:'users',name:'用户与权限',icon:User},{id:'audit',name:'操作审计',icon:Document},{id:'releases',name:'版本管理',icon:Upload},{id:'settings',name:'系统设置',icon:Setting},{id:'security',name:'安全中心',icon:Lock}]
const page=ref('overview'), collapsed=ref(false), dark=ref(localStorage.getItem('rd-theme')==='dark')
const logged=ref(false), booting=ref(true), loginBusy=ref(false), login=reactive({username:'admin',password:''})
const snapshot=ref<Overview|null>(null), samples=ref<Sample[]>([]), audits=ref<Audit[]>([]), releases=ref<Release[]>([])
const settings=reactive<Settings>({node_name:'',notice:'',registration_open:true})
const csrf=ref(''), busy=ref(false), failed=ref(false), error=ref(''), receivedAt=ref(0), now=ref(Date.now()), auto=ref(true)
const query=ref(''), filter=ref('all'), group=ref(''), devicePage=ref(1), auditQuery=ref(''), auditPage=ref(1)
const editing=ref(false), editingID=ref(''), deviceForm=reactive<DeviceMeta>({alias:'',group:'',notes:'',disabled:false}), saving=ref(false)
const publishing=ref(false), releaseText=ref('')
const userRole=ref(''),userName=ref(''),users=ref<{id:string;name:string;role:string;created:number}[]>([]),newUser=reactive({name:'',role:'viewer'}),newToken=ref('')
const settingsLoading=ref(false)
const detailOpen=ref(false),detailID=ref(''),detailBusy=ref(false),detailHistory=ref<Sample[]>([])
const detailDevice=computed(()=>devices.value.find(d=>d.device.id===detailID.value)??null)
const reportedCount=computed(()=>devices.value.filter(d=>d.telemetry).length)
const freshReports=computed(()=>devices.value.filter(d=>telemetryState(d,snapshot.value?.server_time,healthy.value)==='fresh').length)
const reportedSSH=computed(()=>devices.value.filter(d=>telemetryState(d,snapshot.value?.server_time,healthy.value)==='fresh'&&d.telemetry?.report.hosting.ssh_listening).length)
async function inspectDevice(d:Device){detailID.value=d.device.id;detailOpen.value=true;detailHistory.value=[];await refreshDeviceDetail()}
async function refreshDeviceDetail(){if(!detailID.value||detailBusy.value)return;detailBusy.value=true;const id=detailID.value;try{const d=await api<Device>(`devices/${id}`);if(id===detailID.value){detailHistory.value=d.telemetry?.history??[];const i=snapshot.value?.managed_devices.findIndex(v=>v.device.id===id)??-1;if(snapshot.value&&i>=0)snapshot.value.managed_devices[i]=d}}catch(e){ElMessage.error(showError(e))}finally{detailBusy.value=false}}

let detailsGeneration=0
const canEdit=computed(()=>healthy.value&&userRole.value==='admin'&&!settingsLoading.value)
const canCloseSessions=computed(()=>healthy.value&&['admin','operator'].includes(userRole.value))
const visibleMenus=computed(()=>menus.filter(m=>m.id!=='users'||userRole.value==='admin'))
let poll:number|undefined, clock:number|undefined
const controllers=new Set<AbortController>()
const status=computed(()=>connectionStatus(snapshot.value,receivedAt.value,now.value,failed.value))
const healthy=computed(()=>status.value==='online')
const statusLabel=computed(()=>({online:'服务端在线',unreachable:'服务端失联',checking:'连接检查中',stale:'状态已过期',degraded:'服务端状态异常'}[status.value as string]??'状态未知'))
const statusType=computed(()=>healthy.value?'success':status.value==='checking'?'info':'danger')
const title=computed(()=>menus.find(x=>x.id===page.value)?.name??'运行总览')
const sample=computed(()=>snapshot.value?.server.sample)
const devices=computed(()=>snapshot.value?.managed_devices??[])
const groups=computed(()=>[...new Set(devices.value.map(d=>d.meta.group).filter(Boolean))].sort())
const filteredDevices=computed(()=>devices.value.filter(d=>{
 const matches=`${d.device.id} ${d.device.name} ${d.meta.alias} ${d.meta.group} ${d.telemetry?.report.system.os_version??''} ${d.telemetry?.report.agent_version??''} ${d.telemetry?.observed_ip??''} ${d.telemetry?.report.system.gpus?.map(g=>g.name).join(' ')??''}`.toLowerCase().includes(query.value.toLowerCase())
 return matches&&(!group.value||d.meta.group===group.value)&&(filter.value==='all'||filter.value==='online'&&d.online||filter.value==='offline'&&!d.online||filter.value==='blocked'&&d.meta.disabled)
}))
const pagedDevices=computed(()=>filteredDevices.value.slice((devicePage.value-1)*10,devicePage.value*10))
const filteredAudit=computed(()=>audits.value.filter(a=>`${a.action} ${a.target} ${a.actor}`.toLowerCase().includes(auditQuery.value.toLowerCase())))
const pagedAudit=computed(()=>filteredAudit.value.slice((auditPage.value-1)*15,auditPage.value*15))
const sessions=computed(()=>snapshot.value?.sessions??[])
const percent=(part:number|null|undefined,total:number|null|undefined)=>part==null||!total?null:Math.min(100,part/total*100)
const pct=(value:number|null|undefined)=>value==null?'未采集':`${value.toFixed(1)}%`
const time=(v:string|number|undefined)=>!v?'—':new Date(typeof v==='number'?v*1000:v).toLocaleString('zh-CN',{hour12:false})
const uptime=(v:number|undefined)=>v==null?'—':`${Math.floor(v/86400)} 天 ${Math.floor(v%86400/3600)} 小时 ${Math.floor(v%3600/60)} 分钟`
const metricValues=(key:keyof Sample)=>samples.value.map(s=>typeof s[key]==='number'?s[key] as number:null)
const showError=(e:unknown)=>e instanceof Error?e.message:'操作失败'

async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
 const controller=new AbortController();controllers.add(controller)
 const timer=window.setTimeout(()=>controller.abort(),4500)
 try {
  const response=await fetch(`/v1/admin/${path}`,{method,credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json',...(body===undefined?{}:{'Content-Type':'application/json'}),...(csrf.value?{'X-RD-CSRF':csrf.value}:{})},body:body===undefined?undefined:JSON.stringify(body)})
  const data=await response.json()
  if(!response.ok){if(response.status===401&&path!=='login'){logged.value=false;csrf.value=''};throw new Error(data.error??`请求失败 (${response.status})`)}
  return data as T
 } finally{window.clearTimeout(timer);controllers.delete(controller)}
}
async function loadPage(){
 const target=page.value, generation=++detailsGeneration
 const current=()=>generation===detailsGeneration&&page.value===target
 settingsLoading.value=target==='settings'
 try{
  if(target==='audit'){
   const a=await api<Audit[]>('console-audit')
   const b=await api<{at:number;actor:string;action:string;object:string}[]>('audit')
   if(current())audits.value=[...a,...b.map(x=>({at:new Date(x.at*1000).toISOString(),actor:x.actor,action:x.action,target:x.object,result:'success'}))].sort((a,b)=>b.at.localeCompare(a.at))
  }
  if(target==='users'){const data=await api<typeof users.value>('users');if(current())users.value=data}
  if(target==='settings'){const data=await api<Settings>('settings');if(current())Object.assign(settings,data)}
  if(target==='releases'){
   const es=await api<{manifest:{version:string;url:string;sha256:string;platform:string;issued_at:number}}[]>('releases')
   if(current())releases.value=es.map(x=>({version:x.manifest.version,url:x.manifest.url,sha256:x.manifest.sha256,notes:x.manifest.platform,published_at:new Date(x.manifest.issued_at*1000).toISOString()}))
  }
  if(target==='metrics'||!samples.value.length){const data=await api<{samples:Sample[]}>('metrics');if(current())samples.value=data.samples}
 }catch(e){if(current())ElMessage.error(showError(e))}
 finally{if(generation===detailsGeneration)settingsLoading.value=false}
}
async function refresh(withDetails=false){
 if(!logged.value||busy.value)return
 busy.value=true
 try{
  const data=await api<Overview>('overview');snapshot.value=data;receivedAt.value=Date.now();now.value=Date.now();failed.value=false;error.value=''
  const newest=data.server.sample
  if(!samples.value.length||samples.value[samples.value.length-1].at!==newest.at){samples.value.push(newest);if(samples.value.length>720)samples.value.shift()}
  if(withDetails)await loadPage()
 }catch(e){failed.value=true;error.value=showError(e)}finally{busy.value=false}
}
async function signIn(){loginBusy.value=true;error.value='';try{const result=await api<{csrf:string;role:string;username:string}>('login','POST',login);csrf.value=result.csrf;userRole.value=result.role;userName.value=result.username;login.password='';logged.value=true;await refresh(true)}catch(e){error.value=showError(e)}finally{loginBusy.value=false}}
async function signOut(){try{await api('logout','POST',{})}catch(e){ElMessage.error(showError(e));return};logged.value=false;detailOpen.value=false;detailHistory.value=[];csrf.value='';snapshot.value=null;samples.value=[];newToken.value='';receivedAt.value=0;error.value=''}
function go(id:string){page.value=id;window.location.hash=id;void loadPage()}
function theme(){dark.value=!dark.value;document.documentElement.classList.toggle('dark',dark.value);localStorage.setItem('rd-theme',dark.value?'dark':'light')}
function edit(d:Device){editingID.value=d.device.id;Object.assign(deviceForm,d.meta);editing.value=true}
async function saveDevice(){saving.value=true;try{await api(`devices/${editingID.value}`,'PATCH',deviceForm);editing.value=false;ElMessage.success('设备管理信息已保存');await refresh()}catch(e){ElMessage.error(showError(e))}finally{saving.value=false}}
async function saveSettings(){saving.value=true;try{await api('settings','PUT',settings);ElMessage.success('系统配置已保存');await refresh()}catch(e){ElMessage.error(showError(e))}finally{saving.value=false}}
async function closeSession(id:string){try{await ElMessageBox.confirm('将断开这条经过服务器的 SSH 中继连接。直连会话不受此操作控制。','确认断开',{type:'warning'});await api('session-close','POST',{id});ElMessage.success('中继连接已关闭');await refresh()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(showError(e))}}
async function publish(){saving.value=true;try{await api('releases','POST',JSON.parse(releaseText.value));publishing.value=false;releaseText.value='';ElMessage.success('签名清单已验证并登记');await loadPage()}catch(e){ElMessage.error(showError(e))}finally{saving.value=false}}
async function createUser(){try{const r=await api<{token:string}>('users','POST',newUser);newToken.value=r.token;newUser.name='';await loadPage()}catch(e){ElMessage.error(showError(e))}}
async function removeUser(id:string,name:string){try{await ElMessageBox.confirm(`撤销 ${name} 的管理访问？设备本地远控授权不受影响。`,'撤销访问',{type:'warning'});await api(`users?id=${encodeURIComponent(id)}`,'DELETE');await loadPage()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(showError(e))}}
function exportDevices(){const rows=[['设备ID','设备名称','别名','分组','状态','操作系统','Agent版本','CPU','显卡','内存字节','来源IP','最近报告'],...filteredDevices.value.map(d=>[d.device.id,d.device.name,d.meta.alias,d.meta.group,d.meta.disabled?'已禁用':!healthy.value?'状态未知':d.online?'在线':'离线',d.telemetry?.report.system.os_version??'',d.telemetry?.report.agent_version??'',d.telemetry?.report.system.cpu_model??'',d.telemetry?.report.system.gpus?.map(g=>g.name).join('; ')??'',d.telemetry?.report.sample.memory_total??'',d.telemetry?.observed_ip??'',d.telemetry?.received_at??''])];const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='RemoteDesk-devices.csv';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
function hashChanged(){const id=location.hash.slice(1);if(menus.some(x=>x.id===id)){page.value=id;if(logged.value)void loadPage()}}
function visibilityChanged(){if(!document.hidden&&logged.value)void refresh(true)}
onMounted(async()=>{
 document.documentElement.classList.toggle('dark',dark.value);hashChanged()
 window.addEventListener('hashchange',hashChanged);document.addEventListener('visibilitychange',visibilityChanged)
 try{const me=await api<{csrf:string;role:string;username:string}>('me');csrf.value=me.csrf;userRole.value=me.role;userName.value=me.username;logged.value=true;await refresh(true)}catch{logged.value=false}finally{booting.value=false}
 poll=window.setInterval(()=>{if(auto.value&&!document.hidden)void refresh()},5000)
 clock=window.setInterval(()=>{now.value=Date.now()},1000)
})
onUnmounted(()=>{window.clearInterval(poll);window.clearInterval(clock);controllers.forEach(c=>c.abort());window.removeEventListener('hashchange',hashChanged);document.removeEventListener('visibilitychange',visibilityChanged)})
</script>

<template>
 <div v-if="booting" class="boot">RemoteDesk · 正在连接管理服务</div>
 <div v-else-if="!logged" class="login-shell">
  <section class="login-intro"><div class="brand"><span class="brand-mark">R</span>RemoteDesk<span class="brand-suffix">ADMIN</span></div><div><span class="eyebrow">ONE CONSOLE. YOUR INFRASTRUCTURE.</span><h1>掌握每一次连接。<br><span>让远程管理更简单。</span></h1><p>服务器、设备、加密中继与运行状态，集中在一个管理后台。无需分别部署前端和后端。</p><div class="login-features"><span>服务端一体部署</span><span>真实状态监控</span><span>端到端连接授权</span></div></div><small>RemoteDesk Server · Vue 3 / Element Plus</small></section>
  <section class="login-side"><el-card class="login-card" shadow="never"><div class="login-heading"><h2>登录管理控制台</h2><p>使用服务器初始化时生成的管理凭证</p></div><el-form @submit.prevent="signIn" label-position="top"><el-form-item label="管理员账号"><el-input v-model="login.username" autocomplete="username" size="large"/></el-form-item><el-form-item label="管理密码"><el-input v-model="login.password" type="password" show-password autocomplete="current-password" size="large" placeholder="服务器 admin.token 中的随机密码"/></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/><el-button type="primary" native-type="submit" :loading="loginBusy" class="login-submit" size="large">登录控制台</el-button></el-form><div class="login-note">没有公开默认密码。账号为 admin，密码在服务端私有数据目录的 admin.token 文件中；其他用户使用分配的访问令牌作为密码。</div></el-card><small>HTTPS 安全连接 · 会话凭证不写入浏览器本地存储</small></section>
 </div>
 <div v-else class="console" :class="{collapsed}">
  <aside class="sidebar"><div class="brand"><span class="brand-mark">R</span><span v-if="!collapsed">RemoteDesk<small>管理控制台</small></span></div><div v-if="!collapsed" class="nav-group">工作空间</div><nav><button v-for="item in visibleMenus" :key="item.id" :title="item.name" :class="{active:page===item.id}" @click="go(item.id)"><el-icon><component :is="item.icon"/></el-icon><span v-if="!collapsed">{{ item.name }}</span><span v-if="!collapsed&&item.id==='devices'" class="nav-count">{{ devices.length }}</span></button></nav><div class="sidebar-footer"><i class="status-dot" :class="{good:healthy}"/><template v-if="!collapsed"><div>{{ statusLabel }}<small>Server {{ snapshot?.version??'—' }}</small></div></template></div></aside>
  <section class="workspace"><header class="topbar"><div class="header-left"><el-button text circle :icon="Fold" aria-label="展开或折叠导航" @click="collapsed=!collapsed"/><el-breadcrumb><el-breadcrumb-item>RemoteDesk</el-breadcrumb-item><el-breadcrumb-item>{{ title }}</el-breadcrumb-item></el-breadcrumb></div><div class="header-right"><el-tag :type="statusType" effect="light" round><i class="status-dot" :class="{good:healthy}"/>{{ statusLabel }}</el-tag><el-button text circle :icon="dark?Sunny:Moon" aria-label="切换主题" @click="theme"/><div class="avatar">A</div><span class="admin-name">{{ userName==='root'?'admin':userName }}</span><el-button text circle :icon="SwitchButton" aria-label="退出登录" @click="signOut"/></div></header>
  <main>
   <div class="page-heading"><div><div class="eyebrow">REMOTEDESK / OPERATIONS</div><h1>{{ title }}</h1><p>{{ page==='overview'?'服务器启动后自动出现在这里。所有指标来自当前节点。':'统一管理你的远程连接基础设施' }}</p></div><div class="heading-actions"><span class="auto-label">自动刷新</span><el-switch v-model="auto"/><el-button :icon="Refresh" :loading="busy" @click="refresh(true)">刷新</el-button></div></div>
   <el-alert v-if="!healthy" :title="statusLabel" :description="error||'页面中的历史数据仅供参考，不能作为当前在线状态；写入操作暂不可用。'" type="warning" show-icon :closable="false" class="mb"/>
   <el-alert v-if="snapshot?.notice" :title="snapshot.notice" type="info" :closable="false" class="mb"/>
   <template v-if="page==='overview'">
    <div class="kpi-grid"><el-card shadow="never"><div class="kpi-label">当前服务器<el-icon><Monitor/></el-icon></div><strong :class="{'positive':healthy}">{{ healthy?'在线':'待确认' }}</strong><div class="kpi-foot">{{ snapshot?.server.name??'读取中' }} · {{ snapshot?.server.os??'—' }}</div></el-card><el-card shadow="never"><div class="kpi-label">在线设备<el-icon><Connection/></el-icon></div><strong>{{ snapshot?.online??'—' }}<small>/ {{ devices.length }} 台</small></strong><div class="kpi-foot">设备心跳超时 20 秒转为离线</div></el-card><el-card shadow="never"><div class="kpi-label">SSH 中继连接<el-icon><Lock/></el-icon></div><strong>{{ snapshot?.active_ssh_relay??'—' }}<small>条活动连接</small></strong><div class="kpi-foot">仅统计实际经过本服务器的连接</div></el-card><el-card shadow="never"><div class="kpi-label">媒体中继转发<el-icon><TrendCharts/></el-icon></div><strong class="compact-number">{{ formatBytes(snapshot?.media_relay?.forwarded_payload_bytes) }}</strong><div class="kpi-foot">自本次启动以来的加密载荷</div></el-card></div>
    <div class="content-grid"><el-card shadow="never"><template #header><div class="panel-heading"><div><h3>服务器状态</h3><span>本机自动注册 · 单节点部署</span></div><el-tag :type="statusType">{{ statusLabel }}</el-tag></div></template><div class="server-identity"><span class="server-icon"><el-icon><Monitor/></el-icon></span><div><h3>{{ snapshot?.server.name??'—' }}</h3><p>{{ snapshot?.server.hostname??'—' }} / {{ snapshot?.server.os??'—' }} {{ snapshot?.server.arch??'' }}</p></div><el-button text type="primary" @click="go('nodes')">查看节点</el-button></div><div class="resource-row"><div><label>CPU 使用率<span>{{ pct(sample?.cpu_percent) }}</span></label><el-progress :percentage="sample?.cpu_percent??0" :show-text="false" :stroke-width="7"/></div><div><label>主机内存<span>{{ pct(percent(sample?.memory_used,sample?.memory_total)) }}</span></label><el-progress :percentage="percent(sample?.memory_used,sample?.memory_total)??0" :show-text="false" :stroke-width="7"/></div></div><div class="server-facts"><div><small>运行时长</small>{{ uptime(snapshot?.server.uptime_seconds) }}</div><div><small>最近心跳</small>{{ time(snapshot?.server.heartbeat_at) }}</div><div><small>CPU 逻辑核心</small>{{ snapshot?.server.cpu_cores??'—' }} 个逻辑核心</div><div><small>进程驻留内存</small>{{ formatBytes(sample?.process_rss) }}</div></div></el-card>
    <el-card shadow="never"><template #header><div class="panel-heading"><div><h3>CPU 运行趋势</h3><span>真实采样，不使用模拟数据</span></div><el-button text @click="go('metrics')">更多指标</el-button></div></template><Sparkline :values="metricValues('cpu_percent')" :ceiling="100" unit="%"/><div class="chart-summary"><span>接收 <b>{{ formatBytes(sample?.rx_per_second) }}/s</b></span><span>发送 <b>{{ formatBytes(sample?.tx_per_second) }}/s</b></span></div><p class="muted small">网卡流量为主机范围，不等同于远控业务流量。</p></el-card></div>
    <el-card shadow="never" class="mt"><template #header><div class="panel-heading"><h3>最近注册的设备</h3><el-button text type="primary" @click="go('devices')">全部设备</el-button></div></template><el-table :data="[...devices].sort((a,b)=>b.device.registered_at-a.device.registered_at).slice(0,5)" empty-text="暂无设备。客户端注册后将自动显示。"><el-table-column label="设备名称" min-width="180"><template #default="{row}"><b>{{ row.meta.alias||row.device.name }}</b></template></el-table-column><el-table-column prop="device.id" label="设备 ID" min-width="150"/><el-table-column label="分组"><template #default="{row}">{{ row.meta.group||'未分组' }}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.meta.disabled?'danger':healthy&&row.online?'success':'info'" size="small">{{ row.meta.disabled?'已禁用':!healthy?'状态未知':row.online?'在线':'离线' }}</el-tag></template></el-table-column><el-table-column label="最后在线" min-width="180"><template #default="{row}">{{ time(row.last_seen) }}</template></el-table-column></el-table></el-card>
   </template>
   <template v-else-if="page==='nodes'"><el-card shadow="never"><template #header><div class="panel-heading"><div><h3>服务器节点 · 1 个本地节点</h3><span>上传并启动服务端即可显示，无需安装额外监控包</span></div></div></template><el-descriptions :column="2" border><el-descriptions-item label="节点名称">{{ snapshot?.server.name }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusType">{{ statusLabel }}</el-tag></el-descriptions-item><el-descriptions-item label="主机">{{ snapshot?.server.hostname }}</el-descriptions-item><el-descriptions-item label="版本">{{ snapshot?.version }}</el-descriptions-item><el-descriptions-item label="系统">{{ snapshot?.server.os }} / {{ snapshot?.server.arch }}</el-descriptions-item><el-descriptions-item label="运行时长">{{ uptime(snapshot?.server.uptime_seconds) }}</el-descriptions-item><el-descriptions-item label="启动时间">{{ time(snapshot?.server.started_at) }}</el-descriptions-item><el-descriptions-item label="数据存储">{{ snapshot?.server.store }}</el-descriptions-item></el-descriptions><el-table :data="snapshot?.server.components??[]" class="mt"><el-table-column prop="name" label="服务组件"/><el-table-column prop="listen" label="监听地址"/><el-table-column label="内部状态"><template #default="{row}"><el-tag :type="healthy&&row.state==='ready'?'success':'info'">{{ !healthy?'状态未知':row.state==='ready'?'已就绪':row.state==='disabled'?'未启用':row.state }}</el-tag></template></el-table-column><el-table-column prop="detail" label="说明" min-width="260"/></el-table><el-alert title="已就绪表示本机监听已建立，不代表公网防火墙、云安全组和所有 NAT 场景均已打通。服务停止后，本页面会标为失联。" type="info" :closable="false" class="mt"/></el-card></template>
   <template v-else-if="page==='devices'">
    <div class="kpi-grid three"><el-card shadow="never"><div class="kpi-label">已上报设备</div><strong>{{reportedCount}}</strong><div class="kpi-foot">当前服务进程收到过的报告</div></el-card><el-card shadow="never"><div class="kpi-label">有效设备报告</div><strong>{{healthy?freshReports:'—'}}</strong><div class="kpi-foot">在线且 45 秒内收到报告</div></el-card><el-card shadow="never"><div class="kpi-label">SSH 回环端口可连接</div><strong>{{healthy?reportedSSH:'—'}}</strong><div class="kpi-foot">仅有效报告，不代表 SSH 登录成功</div></el-card></div>
    <el-card shadow="never" class="mt"><div class="filters"><el-input v-model="query" :prefix-icon="Search" placeholder="搜索名称 / ID / 系统 / IP / 显卡" clearable @input="devicePage=1"/><el-select v-model="filter" @change="devicePage=1"><el-option label="全部状态" value="all"/><el-option label="在线设备" value="online"/><el-option label="离线设备" value="offline"/><el-option label="已禁用" value="blocked"/></el-select><el-select v-model="group" placeholder="全部分组" clearable @change="devicePage=1"><el-option v-for="g in groups" :key="g" :label="g" :value="g"/></el-select><el-button :icon="Download" @click="exportDevices">导出 CSV</el-button></div>
     <el-table :data="pagedDevices" empty-text="暂无设备：客户端完成初始化、注册并启动主机后将出现在这里。">
      <el-table-column label="名称 / ID" min-width="190"><template #default="{row}"><b>{{row.meta.alias||row.device.name}}</b><small class="subline">{{row.device.id}} · {{row.meta.group||'未分组'}}</small></template></el-table-column>
      <el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="row.meta.disabled?'danger':healthy&&row.online?'success':'info'">{{row.meta.disabled?'已禁用':!healthy?'状态未知':row.online?'在线':'离线'}}</el-tag></template></el-table-column>
      <el-table-column label="系统 / Agent" min-width="180"><template #default="{row}">{{row.telemetry?.report.system.os_version||'未上报'}}<small class="subline">{{row.telemetry?.report.system.arch||'—'}} · {{row.telemetry?.report.agent_version||'—'}}</small></template></el-table-column>
      <el-table-column label="CPU / 内存" min-width="140"><template #default="{row}">{{telemetryState(row,snapshot?.server_time,healthy)==='fresh'?pct(row.telemetry?.report.sample.cpu_percent):'非实时'}}<small class="subline">{{formatBytes(row.telemetry?.report.sample.memory_total)}} RAM</small></template></el-table-column>
      <el-table-column label="来源 IP / 最近报告" min-width="175"><template #default="{row}">{{row.telemetry?.observed_ip||'未上报'}}<small class="subline">{{time(row.telemetry?.received_at)}}</small></template></el-table-column>
      <el-table-column label="操作" width="125" fixed="right"><template #default="{row}"><el-button link type="primary" @click="inspectDevice(row)">详情</el-button><el-button link type="primary" :disabled="!canEdit" @click="edit(row)">管理</el-button></template></el-table-column>
     </el-table><div class="table-footer"><span>共 {{filteredDevices.length}} 台设备 · 详情包含硬件、网络、权限配置与采样历史</span><el-pagination v-model:current-page="devicePage" :page-size="10" :total="filteredDevices.length" layout="prev,pager,next"/></div>
    </el-card>
   </template>
   <template v-else-if="page==='sessions'"><div class="kpi-grid three"><el-card shadow="never"><div class="kpi-label">活动 SSH 中继</div><strong>{{ snapshot?.active_ssh_relay??'—' }}</strong></el-card><el-card shadow="never"><div class="kpi-label">有效媒体中继授权</div><strong>{{ snapshot?.media_relay?.valid_grants??'未启用' }}</strong></el-card><el-card shadow="never"><div class="kpi-label">直连 P2P 会话</div><strong class="compact-number">未上报</strong><div class="kpi-foot">不能通过中继数反推直连数</div></el-card></div><el-card shadow="never" class="mt"><template #header><h3>信令与 SSH 中继会话</h3></template><el-table :data="sessions" empty-text="暂无信令或中继会话"><el-table-column prop="id" label="会话 ID" min-width="230" show-overflow-tooltip/><el-table-column prop="kind" label="类型" width="90"/><el-table-column prop="from" label="来源设备" min-width="140"/><el-table-column prop="to" label="目标设备" min-width="140"/><el-table-column label="状态" width="120"><template #default="{row}"><el-tag :type="!healthy||row.closed?'info':row.paired?'success':'warning'">{{ !healthy?'状态未知':row.closed?'已结束':row.paired?'中继连接中':'协调中' }}</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button link type="danger" :disabled="!canCloseSessions||!row.paired||row.closed" @click="closeSession(row.id)">断开中继</el-button></template></el-table-column></el-table><el-alert title="这里显示服务器可观测的会话。媒体授权数不等于已建立桌面连接数；已建立的独立直连会话不能从此页面强制断开。" type="info" :closable="false" class="mt"/></el-card></template>
   <template v-else-if="page==='metrics'"><div class="content-grid"><el-card shadow="never"><template #header><h3>CPU 使用率</h3></template><Sparkline :values="metricValues('cpu_percent')" :ceiling="100" unit="%"/></el-card><el-card shadow="never"><template #header><h3>主机内存使用率</h3></template><Sparkline :values="samples.map(s=>percent(s.memory_used,s.memory_total))" :ceiling="100" unit="%"/></el-card><el-card shadow="never"><template #header><h3>网卡接收速率</h3></template><Sparkline :values="metricValues('rx_per_second').map(x=>x===null?null:x/1024)" unit="KiB/s"/></el-card><el-card shadow="never"><template #header><h3>网卡发送速率</h3></template><Sparkline :values="metricValues('tx_per_second').map(x=>x===null?null:x/1024)" unit="KiB/s"/></el-card></div><el-card shadow="never" class="mt"><el-descriptions :column="3" border><el-descriptions-item label="内存 已用 / 总量">{{ formatBytes(sample?.memory_used) }} / {{ formatBytes(sample?.memory_total) }}</el-descriptions-item><el-descriptions-item label="磁盘 已用 / 总量">{{ formatBytes(sample?.disk_used) }} / {{ formatBytes(sample?.disk_total) }}</el-descriptions-item><el-descriptions-item label="进程 RSS">{{ formatBytes(sample?.process_rss) }}</el-descriptions-item><el-descriptions-item label="Go 堆内存">{{ formatBytes(sample?.heap_bytes) }}</el-descriptions-item><el-descriptions-item label="Go 协程">{{ sample?.goroutines??'—' }}</el-descriptions-item><el-descriptions-item label="HTTP 累计请求">{{ snapshot?.server.total_requests??'—' }}</el-descriptions-item></el-descriptions><p class="muted small">最多保留 720 个采样点，约 1 小时；服务重启后重新采样。不支持或首次尚未取得的指标显示“未采集”，不是 0。容器内的 /proc 可能反映宿主机而非容器配额。</p></el-card></template>
   <template v-else-if="page==='users'"><el-card shadow="never"><template #header><h3>用户与角色</h3></template><p class="muted">每个用户使用独立随机访问令牌登录；服务端只保存令牌哈希。删除用户立即使其管理会话失效。</p><div class="filters"><el-input v-model="newUser.name" maxlength="100" placeholder="用户名称"/><el-select v-model="newUser.role"><el-option label="只读用户" value="viewer"/><el-option label="会话操作员" value="operator"/><el-option label="管理员" value="admin"/></el-select><el-button type="primary" :disabled="!canEdit" @click="createUser">创建用户</el-button></div><el-alert v-if="newToken" type="warning" title="访问令牌仅显示这一次，请保存到私密位置" :closable="false"><el-input :model-value="newToken" type="password" show-password readonly/><el-button text @click="newToken=''">隐藏令牌</el-button></el-alert><el-table :data="users" empty-text="暂无其他用户，内置 admin 不计入此表"><el-table-column prop="name" label="用户"/><el-table-column prop="role" label="角色"/><el-table-column label="创建时间" min-width="190"><template #default="{row}">{{ time(row.created) }}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button text type="danger" :disabled="!canEdit" @click="removeUser(row.id,row.name)">撤销访问</el-button></template></el-table-column></el-table></el-card></template>
   <template v-else-if="page==='audit'"><el-card shadow="never"><div class="filters"><el-input v-model="auditQuery" :prefix-icon="Search" placeholder="搜索动作 / 操作目标 / 操作者" clearable @input="auditPage=1"/></div><el-table :data="pagedAudit" empty-text="暂无审计记录"><el-table-column label="时间" min-width="180"><template #default="{row}">{{ time(row.at) }}</template></el-table-column><el-table-column prop="actor" label="操作者" width="110"/><el-table-column prop="action" label="动作" min-width="160"/><el-table-column prop="target" label="目标" min-width="180" show-overflow-tooltip/><el-table-column label="结果"><template #default="{row}"><el-tag type="success">{{ row.result==='success'?'成功':row.result }}</el-tag></template></el-table-column></el-table><div class="table-footer"><span>显示监控后台及核心管理审计记录；不记录密码和会话密钥</span><el-pagination v-model:current-page="auditPage" :total="filteredAudit.length" :page-size="15" layout="prev,pager,next"/></div></el-card></template>
   <template v-else-if="page==='releases'"><el-alert title="版本清单必须通过预置公钥验签。自动替换、回滚和 Windows 实机验收仍需单独完成。" type="info" :closable="false" class="mb"/><el-card shadow="never"><template #header><div class="panel-heading"><div><h3>客户端版本</h3><span>下载地址、SHA-256 校验和更新说明</span></div><el-button type="primary" :disabled="!canEdit" @click="publishing=true">登记版本</el-button></div></template><el-table :data="releases" empty-text="尚未登记版本，不会显示虚构的最新版"><el-table-column prop="version" label="版本" width="140"/><el-table-column prop="notes" label="更新说明" min-width="200" show-overflow-tooltip/><el-table-column prop="sha256" label="SHA-256" min-width="230" show-overflow-tooltip/><el-table-column label="登记时间" min-width="180"><template #default="{row}">{{ time(row.published_at) }}</template></el-table-column><el-table-column label="下载" width="100"><template #default="{row}"><a :href="row.url" target="_blank" rel="noopener noreferrer">下载安装包</a></template></el-table-column></el-table></el-card></template>
   <template v-else-if="page==='settings'"><el-card shadow="never" class="settings-card"><template #header><h3>基础配置</h3></template><el-form label-position="top" :disabled="settingsLoading"><el-form-item label="服务器节点名称"><el-input v-model="settings.node_name" maxlength="100" show-word-limit/></el-form-item><el-form-item label="开放新设备注册"><el-switch v-model="settings.registration_open"/><span class="muted inline-note">关闭后拒绝新的注册请求；已有设备可继续心跳</span></el-form-item><el-form-item label="后台通知"><el-input v-model="settings.notice" type="textarea" :rows="4" maxlength="2000" show-word-limit/></el-form-item><el-button type="primary" :disabled="!canEdit" :loading="saving" @click="saveSettings">保存配置</el-button></el-form><el-divider/><p class="muted">监听端口、TLS 证书和中继公网地址在服务器私有配置文件中设置；不通过网页随意改端口或覆盖密钥。</p></el-card></template>
   <template v-else-if="page==='security'"><div class="content-grid"><el-card shadow="never"><template #header><h3>管理员访问</h3></template><el-descriptions :column="1" border><el-descriptions-item label="当前账号">{{ userName==='root'?'admin':userName }}</el-descriptions-item><el-descriptions-item label="角色">{{ userRole }}</el-descriptions-item><el-descriptions-item label="会话有效期">8 小时，退出登录立即撤销该会话</el-descriptions-item><el-descriptions-item label="浏览器凭证">Secure / HttpOnly / SameSite=Strict Cookie</el-descriptions-item><el-descriptions-item label="写入保护">会话 CSRF 校验 + 同源检查</el-descriptions-item><el-descriptions-item label="登录限流">同来源 5 次失败 / 5 分钟窗口</el-descriptions-item></el-descriptions></el-card><el-card shadow="never"><template #header><h3>远程授权边界</h3></template><div class="security-note"><h4>设备私钥不上传到服务端</h4><p>管理后台账号不自动获得远程控制权限。远控仍需要设备本地显式授权。</p><h4>SSH 不直接暴露公网 22</h4><p>客户端通过加密隧道访问被控端回环 SSH 服务，并继续执行正常 SSH 用户认证。</p><h4>禁用不等于撤销所有直连</h4><p>后台禁用阻止中心服务访问并关闭中心 SSH 中继；已有直连仍需从设备本地撤销信任。</p><h4>不提供隐蔽控制或关闭系统安全机制</h4><p>本后台没有安全桌面绕过、秘密授权或关闭 UAC 的开关。</p></div></el-card></div></template>
   <footer class="page-footer"><span>RemoteDesk Admin · 服务端集成部署</span><span>最后取得状态：{{ receivedAt?new Date(receivedAt).toLocaleTimeString('zh-CN',{hour12:false}):'—' }} · {{ auto?'5 秒自动刷新':'自动刷新已暂停' }}</span></footer>
  </main></section>
  <DeviceDetails :open="detailOpen" :device="detailDevice" :healthy="healthy" :server-time="snapshot?.server_time" :history="detailHistory" :loading="detailBusy" @close="detailOpen=false" @refresh="refreshDeviceDetail"/>
  <el-dialog v-model="editing" title="管理设备" width="560px"><el-form label-position="top"><el-form-item label="设备 ID"><el-input :model-value="editingID" disabled/></el-form-item><el-form-item label="管理别名（不修改设备签名名称）"><el-input v-model="deviceForm.alias" maxlength="100"/></el-form-item><el-form-item label="分组"><el-input v-model="deviceForm.group" maxlength="80" placeholder="例如：办公室、服务器、测试设备"/></el-form-item><el-form-item label="备注"><el-input v-model="deviceForm.notes" type="textarea" :rows="3" maxlength="2000"/></el-form-item><el-form-item label="禁止访问中心服务"><el-switch v-model="deviceForm.disabled"/></el-form-item><el-alert title="禁用会阻止中心注册/心跳/信令并关闭中心 SSH 中继，不会远程删除设备，也不能撤销已经建立的独立直连。" type="warning" :closable="false"/></el-form><template #footer><el-button @click="editing=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!canEdit" @click="saveDevice">保存</el-button></template></el-dialog>
  <el-dialog v-model="publishing" title="验证并发布签名版本" width="640px"><p>使用离线签名工具生成清单，粘贴包含 manifest 和 signature 的 JSON。服务端必须已配置 update_public_key；私钥不要上传。</p><el-input v-model="releaseText" type="textarea" :rows="10" placeholder="签名 JSON 清单"/><template #footer><el-button @click="publishing=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!canEdit" @click="publish">验签并发布</el-button></template></el-dialog>
 </div>
</template>
